### ISSUE TITLE
What is `_autopair_tab` supposed to do?

### ISSUE THREAD

**Issue by ajeetdsouza** [jorgebucaran/autopair.fish#7] opened 2022-07-04 07:30 UTC
Hi, thanks for this plugin! I was going through your code and I found the [`_autopair_tab`](https://github.com/jorgebucaran/autopair.fish/blob/main/functions/_autopair_tab.fish) function, which deletes a character from the current token if it matches the regex `\$[^\s]*"$` when the user presses `<Tab>`.

Why is this being done?

**Comment by jorgebucaran** [comment] 2022-07-04 13:28
Fish can't complete variables inside double quotes unless we remove that closing ". You'd almost never run into this when not using Autopair, unless you tried to awkwardly complete like "$<kbd>Tab</kbd>", but then that wouldn't be on us. 🤓

**Closed as completed** 2022-07-04 13:51 UTC

**Comment by ajeetdsouza** [comment] 2022-07-04 13:58
It does cause strange behaviour if your cursor is not at the end of the variable (consider: `"FOO|_BAR"` in which case `<Tab>` would cause the `_` character to get deleted rather than the quote character.

Either way, I found this because I wanted to use the `\t` keybinding in a plugin I maintain, and it looks like that would conflict with this. Do you have any suggestions on how this could be done without overwriting your keybinding?

**Comment by jorgebucaran** [comment] 2022-07-04 14:06
I can't reproduce the scenario you are describing, what should I type out exactly?


> Do you have any suggestions on how this could be done without overwriting your keybinding?

You could check if `_autopair_tab` was defined while inside your own keybinding handler, and call it.

**Comment by ajeetdsouza** [comment] 2022-07-04 14:26
I forgot the `$` sign. If you put your cursor where the `|` is:

```shell
"$FOO|_BAR"
```

Then pressing `<Tab>` deletes the `_` character. Pressing it again results in it getting completed to `"$FOOBAR:"`:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1777663/177173532-5987b94c-6a89-4840-b691-9071e41b4fb2.png">

> You could check if _autopair_tab was defined while inside your own keybinding handler, and call it.

That would need to be updated every time there's a plugin that binds `\t`, so I don't think that's a feasible solution. I asked this on Fish's issue tracker and they advised not to override such a core keybinding.

**Comment by jorgebucaran** [comment] 2022-07-04 15:40
I never said it would be pretty! 😄 

> That would need to be updated every time there's a plugin that binds \t, so I don't think that's a feasible solution.

You can use `bind --user \t` to find all user-defined `\t` bindings before binding `\t` to your own function:

```console
$ bind --user \t
bind \t _autopair_tab
```

Now you know what functions to call inside your function. 

> Then pressing <Tab> deletes the _ character. Pressing it again results in it getting completed to "$FOOBAR:"...

https://github.com/jorgebucaran/autopair.fish/issues/8. I'll fix this ASAP. Thanks!

**Comment by ajeetdsouza** [comment] 2022-07-04 16:00
> You can use `bind --user \t` to find all user-defined `\t` bindings before binding `\t` to your own function:

Still doesn't work -- if everyone does this, all functions would be called in an infinite recursive loop :(

Given how many Fish plugins you've written, I suppose I might as well give you context for what I'm trying to do. I wanted to override the tab-completions for [zoxide](https://github.com/ajeetdsouza/zoxide)'s Fish plugin.

What I want to do is replace the default Fish completer with [fzf](https://github.com/junegunn/fzf) just for the `z` command. For example, a user should be able to type `z foo bar <Tab>`, which would bring up fzf instead of the default completer. Once the user selects an option (say `/home/foo/bar`, the command should be re-written to `z /home/foo/bar`.

Unfortunately, `commandline` cannot be used to write text inside of a completion function -- it works on some systems and doesn't work on others, which is why I was trying to bind the `\t` key.

Regardless, thanks for your help! I don't think there's a way to do this properly in Fish, so I'll have to use a workaround.

**Comment by jorgebucaran** [comment] 2022-07-04 16:07
> Still doesn't work -- if everyone does this, all functions would be called in an infinite recursive loop :(

When you bind `\t`, this overwrites existing bindings, but yes, I agree that you could run into a situation like that if are not careful (or even if you are). 😅 

Have a look at @PatrickF1's excellent https://github.com/PatrickF1/fzf.fish for inspiration.

**Comment by jorgebucaran** [comment] 2022-07-04 16:07
> Still doesn't work -- if everyone does this, all functions would be called in an infinite recursive loop :(

When you bind `\t`, this overwrites existing bindings, but I agree that you could run into a situation like that if are not careful (or even if you are). 😅 

Have a look at @PatrickF1's excellent https://github.com/PatrickF1/fzf.fish for inspiration.
